## tetapan patuh piawai
lang: ms  # bahasa Melayu
repository: kmubiin/suaikata  # metadata tanpa .git
title: suaikata
description: Koleksi ringkas kosa kata

## tetapan bagi Jekyll
url: https://kmubiin.github.io/suaikata
permalink: /:title:output_ext
timezone: Etc/UTC  # tzdata (IANA time zone database)
includes_dir: _muat  # asalnya _includes
# layouts_dir: _layouts  # akan diberi nama lain

theme: jekyll-theme-slate

plugins:
  - jekyll-relative-links
#   - jekyll-seo-tag          # mengikut tema
#   - jekyll-github-metadata  # mengikut tema
defaults:
  -
    scope:
      path: ""  # merangkumi semua laman
    values:
      layout: "default"

show_downloads: false  # mengikut tema

# github:
#   repository_url: https://github.com/kmubiin/suaikata
#   zip_url: https://github.com/kmubiin/suaikata/archive/asal.zip
#   tar_url: https://github.com/kmubiin/suaikata/archive/asal.tar.gz

## lagi tetapan mengikut tema dan laman
## https://jekyllrb.com/docs/configuration/
