## tetapan patuh piawai
lang: ms  # bahasa Melayu
repository: kmubiin/suaikata  # metadata tanpa .git
title: suaikata
description: Koleksi ringkas kosa kata

## tetapan bagi GitHub Pages
theme: jekyll-theme-slate
show_downloads: false
## ---TETAPAN LALAI---
# github:
#   repository_url: https://github.com/kmubiin/suaikata
#   zip_url: https://github.com/kmubiin/suaikata/archive/master.zip
#   tar_url: https://github.com/kmubiin/suaikata/archive/master.tar.gz
## ---TETAPAN LALAI---
## baris di atas sengaja dinyahaktif

## tetapan bagi Jekyll
url: https://kmubiin.github.io/suaikata
permalink: /:title:output_ext
## paparan waktu tzdata (IANA time zone database)
timezone: Etc/UTC
## hasil paparan di luar talian perlu ada tetapan lain
## untuk menyamai hasil paparan di GitHub Pages
## ---TETAPAN LOCALHOST---
# plugins:
# - jekyll-relative-links
# - jekyll-seo-tag          # jika perlu ikut tema
# - jekyll-github-metadata  # jika perlu ikut tema
# defaults:
#   -
#     scope:
#       path: ""  # merangkumi semua laman
#     values:
#       layout: "default"
## ---TETAPAN LOCALHOST---
## baris di atas sengaja dinyahaktif

## lagi tetapan mengikut tema dan laman
## https://jekyllrb.com/docs/configuration/
