## tetapan khas bagi projek suaikata
peringkat: alfa
terbitan: 2.20.0731

## tetapan lazim bagi GitHub Pages
title: suaikata
description: Koleksi ringkas kosa kata
theme: jekyll-theme-slate
show_downloads: false

## paparan pautan
url: https://kmubiin.github.io/suaikata
permalink: /:title:output_ext

## paparan waktu tzdata (IANA time zone database)
timezone: Etc/UTC

## Lagi tetapan mengikut tema dan laman
## https://pages.github.com/themes/
## https://jekyllrb.com/docs/configuration/
